apiVersion: v1
kind: Service
metadata:
  name: export-api
  namespace: gitlab-managed-apps
  labels:
    app: export
spec:
  selector:
    app: export
  ports:
    - name: api
      protocol: TCP
      port: 22022
      targetPort: 22022
---
apiVersion: v1
kind: Service
metadata:
  name: export-api-dev
  namespace: gitlab-managed-apps
  labels:
    app: export-dev
spec:
  selector:
    app: export-dev
  ports:
    - name: api
      protocol: TCP
      port: 22022
      targetPort: 22022
